#!/usr/bin/env python3
"""fibre_eta.py - the fibre over PAIRS (lambda, eta), which is the question fibre.py did not answer.

  Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)

The literature gate on Kawamura-Kodaira-Kojima-Yamashita arXiv:2502.08250 (GATE_KKKY.md) showed
that charge conjugation is invisible unconditionally -- they say so in print -- and that our sign
(-1)^{lambda_1} is not about C at all: it is about which extension of the multiplet to the group
generated by SU(4) and the det = -1 element is chosen, i.e. about the boundary-condition phase eta.

Operationally (HANDOFF.md, verified on 212 partitions): lambda -> lambda + (1,1,1,1) is the SAME
SU(4) irrep and multiplies the character by det(A), which is +1 on the identity component and -1 on
the coset.  So

    eta in {+1,-1}   acts as   (Sigma_lambda, D_lambda)  |-->  (Sigma_lambda, eta * D_lambda)

and the physical observable of a multiplet is that pair.  Two questions, in order:

  1. how large is the fibre of  (lambda, eta) |--> (Sigma, eta*D) ?
  2. is every collision generated by the two relations we already know --
        (a)  (lambda, eta) ~ (lambda*, eta*(-1)^{lambda_1})        [the gate's relation]
        (b)  (lambda, +) ~ (lambda, -)  whenever D_lambda = 0      [Part IV's vanishing class]
     or is there something else?

Exact integer Laurent arithmetic; no floating point.
"""
import collections
import json
import os
from itertools import combinations_with_replacement

from fibre import schur, key, EVEN, ODD

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "outputs")


def dual(l):
    """the conjugate SU(4) irrep, in the canonical representative lambda_4 = 0"""
    return (l[0] - l[3], l[0] - l[2], l[0] - l[1], 0)


def neg(poly):
    return {k: -v for k, v in poly.items()}


def main(MAX=12):
    irreps = [list(c)[::-1] + [0] for c in combinations_with_replacement(range(MAX + 1), 3)]
    irreps = [l for l in irreps if l[0] >= l[1] >= l[2]]
    print("SU(4) irreps with lambda_1 <= %d: %d      pairs (lambda,eta): %d\n"
          % (MAX, len(irreps), 2 * len(irreps)))

    S, D = {}, {}
    for lam in irreps:
        t = tuple(lam)
        S[t], D[t] = schur(lam, EVEN), schur(lam, ODD)

    fib = collections.defaultdict(list)
    for lam in irreps:
        t = tuple(lam)
        for eta in (+1, -1):
            obs = (key(S[t]), key(D[t] if eta == 1 else neg(D[t])))
            fib[obs].append((t, eta))

    sizes = collections.Counter(len(v) for v in fib.values())
    print("classes: %d      fibre sizes: %s\n" % (len(fib), dict(sorted(sizes.items()))))

    # ---- is every collision generated by the two known relations? -------------------
    def predicted(t, eta):
        """the orbit of (lambda,eta) under the two relations we can prove"""
        orb = {(t, eta)}
        d = dual(t)
        if d in S:
            orb.add((d, eta * (-1) ** t[0]))
        if not D[t]:                       # Part IV's vanishing class: eta is unobservable
            orb |= {(x, -e) for (x, e) in list(orb)}
        # close under both
        for (x, e) in list(orb):
            dx = dual(x)
            if dx in S:
                orb.add((dx, e * (-1) ** x[0]))
            if not D[x]:
                orb.add((x, -e))
        return orb

    unexplained = []
    for obs, members in fib.items():
        t, eta = members[0]
        if set(members) != predicted(t, eta):
            unexplained.append((members, sorted(predicted(t, eta))))
    print("fibres NOT generated by the two known relations: %d" % len(unexplained))
    for m, p in unexplained[:5]:
        print("    observed %s   predicted %s" % (sorted(m), p))

    # ---- the anatomy of the degeneracy ---------------------------------------------
    selfconj = [l for l in irreps if dual(tuple(l)) == tuple(l)]
    zclass = [l for l in irreps if not D[tuple(l)]]
    print("\nanatomy")
    print("   self-conjugate irreps (lambda* = lambda) : %d" % len(selfconj))
    print("   in Part IV's vanishing class (D = 0)     : %d" % len(zclass))
    print("   irreps whose eta is UNOBSERVABLE         : %d"
          % sum(1 for l in irreps
                if len({key(D[tuple(l)]), key(neg(D[tuple(l)]))}) == 1
                or any(m[0] == tuple(l) and m[1] == -1 for f in fib.values() if len(f) > 1
                       for m in f if (tuple(l), +1) in f)))
    eta_blind = [l for l in irreps
                 if (tuple(l), +1) in next((f for f in fib.values()
                                            if (tuple(l), +1) in f), [])
                 and (tuple(l), -1) in next((f for f in fib.values()
                                             if (tuple(l), +1) in f), [])]
    print("   ... of which by D = 0                    : %d"
          % sum(1 for l in eta_blind if not D[tuple(l)]))
    print("   ... of which self-conjugate, lambda_1 odd: %d"
          % sum(1 for l in eta_blind if dual(tuple(l)) == tuple(l) and l[0] % 2 == 1))
    print("   total with eta unobservable              : %d of %d" % (len(eta_blind), len(irreps)))

    # ---- dump the DATA, not just the summary: this run is never to be repeated -----
    os.makedirs(OUT, exist_ok=True)
    data = {
        "range": {"lambda_1_max": MAX, "irreps": len(irreps), "pairs": 2 * len(irreps)},
        "characters": {str(list(t)): {"Sigma": sorted(S[t].items()),
                                      "D": sorted(D[t].items())} for t in S},
        "classes": [[[list(t), e] for (t, e) in members] for members in fib.values()],
        "fibre_sizes": {str(k): v for k, v in sorted(sizes.items())},
        "unexplained": [[[list(t), e] for (t, e) in m] for m, _ in unexplained],
        "self_conjugate": [list(l) for l in selfconj],
        "vanishing_class_Z": [list(l) for l in zclass],
        "eta_unobservable": [list(l) for l in eta_blind],
    }
    path = os.path.join(OUT, "fibre_eta.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=1)
    print("\ndata written to outputs/fibre_eta.json  (%d characters, %d classes)"
          % (len(S), len(fib)))
    return fib


if __name__ == "__main__":
    main()
